{% set name = "pybacktrack" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6277fc5263e2a38c1c472435fea612fa9fb7923a14ba33b4dc30ba2e984411e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - gmt >=5.0.0
    - numpy
    - pygplates
    - scipy

test:
  source_files:
    - tests
  imports:
    - pybacktrack
  requires:
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/EarthByte/pyBacktrack
  summary: A tool for reconstructing paleobathymetry on oceanic and continental crust.
  dev_url: https://github.com/EarthByte/pyBacktrack
  doc_url: https://pybacktrack.readthedocs.io
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcannon-gplates
